<a href="https://colab.research.google.com/github/filipematttos/AnaliseDados/blob/main/dicion%C3%A1rios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DICIONÁRIOS { }

In [ ]:
pessoas = {'Pedro': 18, 'Luana': 23, 'Francisco': 42}

In [ ]:
print(pessoas)

{'Pedro': 18, 'Luana': 23, 'Francisco': 42}


In [ ]:
type(pessoas) #para ver o tipo de dados

dict

In [ ]:
dicionario1 = {} #criar um dicionário vazio
dicionario2 = dict() #cria um dicionário vazio


In [ ]:
pessoas['Carla'] = 18 #insere um novo elemento ao dicionário
pessoas

{'Pedro': 18, 'Luana': 23, 'Francisco': 42, 'Carla': 18}

In [ ]:
pessoas.keys() #retona as chaves do dicionário

dict_keys(['Pedro', 'Luana', 'Francisco', 'Carla'])

In [ ]:
pessoas.values() #retorna os valores das chaves

dict_values([18, 23, 42, 18])

In [ ]:
pessoas.items() #retorna todos os elementos do dicionário

dict_items([('Pedro', 18), ('Luana', 23), ('Francisco', 42), ('Carla', 18)])

In [ ]:
pessoas1 = {'nome': 'Fernando','idade': 21, 'nome': 'Gustavo', 'idade': 18} #pergunta de prova: Em um dicionário não é possível colocar duas chaves com o mesmo nome, pois se colocar, ele vai sobrepor.

In [ ]:
pessoas1

{'nome1': 'Fernando',
 'idade1': 21,
 'nome2': 'Gustavo',
 'idade2': 18,
 'sexo': 'M'}

In [ ]:
pessoas1['sexo'] = 'M' #acrescenta a chave 'sexo' e o valor 'm'

In [ ]:
pessoas1

{'nome1': 'Fernando',
 'idade1': 21,
 'nome2': 'Gustavo',
 'idade2': 18,
 'sexo': 'M'}

In [ ]:
pessoas1

{'nome1': 'Fernando',
 'idade1': 21,
 'nome2': 'Gustavo',
 'idade2': 18,
 'sexo': 'M'}

In [ ]:
del pessoas1['idade'] #apaga a chave 'idade1'

pessoas1

NameError: ignored

In [ ]:
pessoas1

{'nome1': 'Fernando', 'nome2': 'Gustavo', 'idade2': 18, 'sexo': 'M'}

**ITERANDO E IMPRIMINDO UM DICIONÁRIO**




In [ ]:
for k, v in pessoas.items():
  print(f'{k} = {v}')

NameError: ignored

**CARREGANDO UM DICIONÁRIO COM O INPUT**

In [ ]:
dados = dict()

dados['nome'] = input('Nome: ')
dados['idade'] = int(input('Idade: '))
dados['salario'] = float(input('Salário: '))

print()

for k,v in dados.items():
  print(f'{k} = {v}')

Nome: filipe
Idade: 334
Salário: 545566

nome = filipe
idade = 334
salario = 545566.0


ESTRUTURA DE DADOS - VETOR:





Os vetores e as matrizes são estruturas de dados estáticas e que suportam apenas um tipo de dado. Quando criamos um vetor numpy vazio, por padrão, é criado o tipo float. Uma vez definido seu tamanho, não é mais possível alterar. São acessador tbm por indices que iniciam em zero, ocupam menos espaço na memória que as listas e são mais rápidos tbm. Para criá-lo é necessário importar a biblioteca numpy.

In [ ]:
import numpy as np

vetor =  np.array([1,2,3,4,5])

In [ ]:
print(vetor)

[1 2 3 4 5]


In [ ]:
type(vetor) #mostra o tipo da variável

numpy.ndarray

In [ ]:
vetor.dtype #trás o tipo do vetor

dtype('int64')

In [ ]:
vetor1 = np.array([2.5, 3.7, 8.2])

In [ ]:
vetor1.dtype #mostra o tipo da variável

dtype('float64')

In [ ]:
nomes = np.array(['Ana', 'Paulo', 'Gustavo'])

In [ ]:
nomes.dtype #a string tem que ser menor que 7 , mostra até que tamanho a string pode ser

dtype('<U7')

In [ ]:
vetor[2] #retorna o valor da posição

3

In [ ]:
vetor[3] = 50  #sobrepões a posição 3 com 50

NameError: ignored

In [ ]:
vetor

NameError: ignored

In [ ]:
vetor.sort() #coloca o vetor em ordem crescente

In [ ]:
vetor

array([ 1,  2,  3,  5, 50])

In [ ]:
vetor + vetor #soma o vetor com ele mesmo

array([  2,   4,   6,  10, 100])

In [ ]:
vetor * 2


array([  2,   4,   6,  10, 100])

In [ ]:
del vetor #apaga todo o vetor

vetor

NameError: ignored

In [ ]:
nomes

array(['Ana', 'Paulo', 'Gustavo'], dtype='<U7')

In [ ]:
#CRIAR UM VETOR COM ARANGE

vetor = np.arange(10) #cria um vetor com númros sequenciais


In [ ]:
vetor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#CRIA UM VETOR COM NÚMEROS ALEATÓRIOS

import random


#cria um vetor com 10 números dentro da faixa de 0 a 100
vetor1 = np.random.randint(100, size=(10))

vetor1

array([65, 28, 16, 24, 86,  2, 81, 64, 83, 55])

**ALGUMAS FUNÇÕES USADAS COM VETORES**:


In [ ]:
np.max(vetor1) #retorna o maior valor do vetor

86

In [ ]:
np.min(vetor1) #retorna o menor valor do vetor

2

In [ ]:
np.mean(vetor1) #retorna a média aritmética dos valores do vetor

50.4

In [ ]:
np.sum(vetor1) #retorna a soma doa valroes do vetor

504

**PARA CRIAR UM VETOR VÁZIO**:

In [ ]:
vetor3 = np.empty(5) #cria um vetor vazio de 5 posições

In [ ]:
vetor3.dtype

dtype('float64')

In [ ]:
vetor3

array([2.12518741e-316, 0.00000000e+000, 7.49088705e+247, 9.76518510e+199,
       8.69555537e-322])

In [ ]:
vetor3[0] = 7
vetor3[1] = 12
vetor3[2] = 55
vetor3[3] = 35
vetor3[4] = 10

In [ ]:
vetor3

array([ 7., 12., 55., 35., 10.])

**CARREGANDO UM VETOR PELO TECLADO:**

In [ ]:
valores = np.empty(5) #cria atumaticamente um vetor tipo float

for i in range(5):
  valores[i] = input('Número:')

print(valores)

Número:1
Número:2
Número:3
Número:4
Número:5
[1. 2. 3. 4. 5.]


In [ ]:
valores.dtype

dtype('float64')

In [ ]:
valores1 = np.empty(5,dtype='int64') #para criar um vetor do tipo inteiro
for i in range(5):
  valores[i] = input('Número:')

print(valores1)

Número:2
Número:5
Número:5
Número:7
Número:8
[2. 5. 5. 7. 8.]


In [ ]:
valores1.dtype

dtype('int64')

In [ ]:
nomes = np.empty(5, dtype='U15') #para criar um vetor do tipo inteiro
for i in range(5):
  nomes[i] = input('Nomes:')

print(nomes)

Nomes:Filipe
Nomes:Julia
Nomes:Fabio
Nomes:Duda
Nomes:Gustavo
['Filipe' 'Julia' 'Fabio' 'Duda' 'Gustavo']



**MATRIZES:**


In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])

In [ ]:
matriz


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matriz.shape #retorna a dimensão da matriz

(2, 3)

In [ ]:
matriz[0,2]

3

**CRIANDO MATRIZES ESPECÍFICAS**

In [ ]:
#MATRIZ IDENTIDADE:  diagonal principal com 1

I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#MATRIZ DIAGONAL: DIAGONAL PRINCIPAL COM NUMEROS DE 0 A 5

D = np.diag(np.arange(5))
print(D)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [ ]:
#MATRIZ DE ZEROS

Z = np.zeros([3,3])
print(Z)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#MATRIZ DE UNS

U = np.ones([3,3])
print(U)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#CRIANDO UMA MATRIZ COM NÚMEROS ALEATÓRIOS

matriz = np.random.randint(100, size=(5,3))
print(matriz)



[[96 17 57]
 [11 48 88]
 [22 36 16]
 [54  6 45]
 [31  5 57]]
